### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by simnovusadmin** [ios-mcn/workflows-permissions#36]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Member Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN Dist | [QA](https://github.com/ios-mcn-ran-distributed/qa/) | Simnovus | Uday Parida | simnovusadmin | Write | xxx |
| RAN Dist | [RAN Dist](https://github.com/ios-mcn-ran-distributed/ios-mcn-ran-distributed/) | Simnovus | Uday Parida | simnovusadmin | Read | xxx |

**Comment by joseajeesh** [comment]
Access provided based on the mail approval from Usha

**Comment by joseajeesh** [comment]
Access revoked based on the request from Uday
