### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by innovators-creators** [ios-mcn/workflows-permissions#37]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN Dist | [QA](https://github.com/ios-mcn-ran-distributed/qa/) | Simnovus | Uday Parida | innovators-creators | Write | xxx |
| RAN Dist | [RAN Dist](https://github.com/ios-mcn-ran-distributed/ios-mcn-ran-distributed/) | Simnovus | Uday Parida | innovators-creators | Read | xxx |

Please remove access to the other user "**_simnovusadmin_**" that was created by me in the [request ticket](https://github.com/ios-mcn/workflows-permissions/issues/36).

**Comment by joseajeesh** [comment]
Done. Send the access Invite. APproved in mail by Usha
