### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by pcsaji** [ios-mcn/workflows-permissions#43]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| CORE | [Repo URL](https://github.com/ios-mcn-core) | C-DAC | Sajimon P C| pcsaji| Read/Write| For core sub project |

**Comment by joseajeesh** [comment]
done
