### ISSUE TITLE
Access Request - Caze Labs intern- Role -Audit and DevOps 

### ISSUE THREAD

**Issue by joseajeesh** [ios-mcn/workflows-permissions#44]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| CORE, RAN Dist,RAN Unified, SMO |  | ICazeLabs |  niveditapa21 |  nivedita.pa21@gmail.com  | Read/Write | Caze Labs Intern, Will handle the audit and Devops work |

**Comment by skdwriting** [comment]
Approved.

**Comment by vinaykz** [comment]
Approved

**Comment by sknrao** [comment]
approved

**Comment by joseajeesh** [comment]
done
