### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by innovators-creators** [ios-mcn/workflows-permissions#55]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| SMO | [Repo URL](https://github.com/ios-mcn-smo) | Simnovus | Uday Parida | innovators-creators | Read | Required to test the SMO integration |

**Comment by joseajeesh** [comment]
done
